"""updated alerts with stripe payment info

Revision ID: 205cfc5952d1
Revises: 9ab95efade3e
Create Date: 2021-08-29 13:42:43.293974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205cfc5952d1'
down_revision = '9ab95efade3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('initial_period_start', sa.Integer(), nullable=True))
    op.add_column('alert', sa.Column('initial_period_end', sa.Integer(), nullable=True))
    op.add_column('alert', sa.Column('period_start', sa.Integer(), nullable=True))
    op.add_column('alert', sa.Column('period_end', sa.Integer(), nullable=True))
    op.add_column('alert', sa.Column('price_id', sa.String(), nullable=True))
    op.add_column('alert', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('alert', sa.Column('stripe_invoice_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert', 'stripe_invoice_id')
    op.drop_column('alert', 'stripe_customer_id')
    op.drop_column('alert', 'price_id')
    op.drop_column('alert', 'period_end')
    op.drop_column('alert', 'period_start')
    op.drop_column('alert', 'initial_period_end')
    op.drop_column('alert', 'initial_period_start')
    # ### end Alembic commands ###
