"""updated alerts to handle payment status

Revision ID: 9ab95efade3e
Revises: 
Create Date: 2021-08-28 20:32:42.654934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab95efade3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('initial_payment', sa.Boolean(), nullable=True))
    op.add_column('alert', sa.Column('payment_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert', 'payment_status')
    op.drop_column('alert', 'initial_payment')
    # ### end Alembic commands ###
