"""add email verification fields to user

Revision ID: a1b2c3d4e5f6
Revises: d9a8a8bbda9d
Create Date: 2026-01-18 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'd9a8a8bbda9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user', sa.Column('email_verification_token', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('token_expiry', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_email_verification_token'), 'user', ['email_verification_token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email_verification_token'), table_name='user')
    op.drop_column('user', 'token_expiry')
    op.drop_column('user', 'email_verification_token')
    op.drop_column('user', 'email_verified')
    # ### end Alembic commands ###
