"""add user report frequency preference

Revision ID: a3b7c9d2e4f1
Revises: d9a8a8bbda9d
Create Date: 2026-01-18 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b7c9d2e4f1'
down_revision = 'd9a8a8bbda9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('report_frequency', sa.String(length=10), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE \"user\" SET report_frequency = 'none' WHERE report_frequency IS NULL")
    # Make column non-nullable after setting defaults
    op.alter_column('user', 'report_frequency',
               existing_type=sa.String(length=10),
               nullable=False,
               server_default='none')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'report_frequency')
    # ### end Alembic commands ###
