"""add mortgage rate model for rate tracking

Revision ID: d9a8a8bbda9d
Revises: 205cfc5952d1
Create Date: 2026-01-10 22:57:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a8a8bbda9d'
down_revision = '205cfc5952d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mortgage_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.String(length=5), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('rate_date', sa.DateTime(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mortgage_rate_zip_code'), 'mortgage_rate', ['zip_code'], unique=False)
    op.create_index(op.f('ix_mortgage_rate_term_months'), 'mortgage_rate', ['term_months'], unique=False)
    op.create_index(op.f('ix_mortgage_rate_rate_date'), 'mortgage_rate', ['rate_date'], unique=False)
    op.create_index('ix_mortgage_rate_zip_term_date', 'mortgage_rate', ['zip_code', 'term_months', 'rate_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mortgage_rate_zip_term_date', table_name='mortgage_rate')
    op.drop_index(op.f('ix_mortgage_rate_rate_date'), table_name='mortgage_rate')
    op.drop_index(op.f('ix_mortgage_rate_term_months'), table_name='mortgage_rate')
    op.drop_index(op.f('ix_mortgage_rate_zip_code'), table_name='mortgage_rate')
    op.drop_table('mortgage_rate')
    # ### end Alembic commands ###
