"""add email log model

Revision ID: f2g3h4i5j6k7
Revises: e1f2a3b4c5d6
Create Date: 2026-01-18 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2g3h4i5j6k7'
down_revision = 'e1f2a3b4c5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_type', sa.String(length=50), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_log_email_type'), 'email_log', ['email_type'], unique=False)
    op.create_index(op.f('ix_email_log_recipient_email'), 'email_log', ['recipient_email'], unique=False)
    op.create_index(op.f('ix_email_log_recipient_user_id'), 'email_log', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_email_log_status'), 'email_log', ['status'], unique=False)
    op.create_index('ix_email_log_type_status', 'email_log', ['email_type', 'status'], unique=False)
    op.create_index('ix_email_log_entity', 'email_log', ['related_entity_type', 'related_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_log_entity', table_name='email_log')
    op.drop_index('ix_email_log_type_status', table_name='email_log')
    op.drop_index(op.f('ix_email_log_status'), table_name='email_log')
    op.drop_index(op.f('ix_email_log_recipient_user_id'), table_name='email_log')
    op.drop_index(op.f('ix_email_log_recipient_email'), table_name='email_log')
    op.drop_index(op.f('ix_email_log_email_type'), table_name='email_log')
    op.drop_table('email_log')
    # ### end Alembic commands ###
