"""add email log model for tracking emails

Revision ID: f4febc54daf0
Revises: d9a8a8bbda9d
Create Date: 2026-01-18 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4febc54daf0'
down_revision = 'd9a8a8bbda9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('trigger_id', sa.Integer(), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('email_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.id'], ),
    sa.ForeignKeyConstraint(['trigger_id'], ['trigger.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_log_recipient_email'), 'email_log', ['recipient_email'], unique=False)
    op.create_index(op.f('ix_email_log_email_type'), 'email_log', ['email_type'], unique=False)
    op.create_index(op.f('ix_email_log_status'), 'email_log', ['status'], unique=False)
    op.create_index(op.f('ix_email_log_sent_at'), 'email_log', ['sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_log_sent_at'), table_name='email_log')
    op.drop_index(op.f('ix_email_log_status'), table_name='email_log')
    op.drop_index(op.f('ix_email_log_email_type'), table_name='email_log')
    op.drop_index(op.f('ix_email_log_recipient_email'), table_name='email_log')
    op.drop_table('email_log')
    # ### end Alembic commands ###
